# -*- coding: utf-8 -*-
"""back end

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/164IVgMqFU_W6zvufzLZrvsasht9v4Qy8
"""

!pip install "graphene>=3.0"

import graphene

# Modelo de produto
class Produto(graphene.ObjectType):
    id = graphene.Int()
    nome = graphene.String()
    preco = graphene.Float()


# Lista inicial de produtos
# Aqui estamos simulando um banco de dados
produtos = [
    {"id": 1, "nome": "Camiseta", "preco": 50.00},
    {"id": 2, "nome": "Tênis", "preco": 120.00}
]


# Consultas GraphQL
class Query(graphene.ObjectType):
    produto = graphene.Field(Produto, id=graphene.Int(required=True))
    produtos = graphene.List(Produto)

    # Buscar um produto pelo ID
    def resolve_produto(root, info, id):
        return next((p for p in produtos if p["id"] == id), None)

    # Buscar todos os produtos
    def resolve_produtos(root, info):
        return produtos


# Mutation para adicionar produto
class AdicionarProduto(graphene.Mutation):

    class Arguments:
        nome = graphene.String(required=True)
        preco = graphene.Float(required=True)

    produto = graphene.Field(Produto)

    def mutate(root, info, nome, preco):
        novo_produto = {
            "id": len(produtos) + 1,
            "nome": nome,
            "preco": preco
        }

        produtos.append(novo_produto)

        return AdicionarProduto(produto=novo_produto)


# Classe principal de mutations
class Mutation(graphene.ObjectType):
    adicionar_produto = AdicionarProduto.Field()


# Criação do schema GraphQL
schema = graphene.Schema(query=Query, mutation=Mutation)

print("Schema GraphQL criado com sucesso!")